### ISSUE TITLE
Inconsistent indentation

### ISSUE THREAD

**Issue by morganchristiansson** [hagen1778/grafana-import-export#4]
This project uses both tabs and spaces. Pick one and use it consistently.

This makes code not line up correctly - for example here https://github.com/hagen1778/grafana-import-export/blob/master/importer.sh#L21

And as a result it's harder to read the code than it needs to be.

**Comment by hagen1778** [comment]
Hi @morganchristiansson 
Thank you very much for finding time to revise the code! And special thanks for alerts support!

**Comment by morganchristiansson** [comment]
Thanks for merging and updating the README.

There's some work left on alert-notifications. I haven't tested creating new alerts and there's a separate API for this. Also importing alerts only works in the import all code-path and can't be imported by filename. This is enough for my  usecase for now but should be improved.

Maybe there's a way to have single code-path for both import all and import by path
